apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  namespace: ashish
spec:
  containers:
    - name: nginx-volume
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-volume
          mountPath: /usr/share/nginx/html
  volumes:
       - name: nginx-volume
         persistentVolumeClaim:
           claimName: my-pvc
     

