apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: ashish

spec:
  containers:
    - name: nginx-cloud
      image: nginx:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: cloud-storage
          mountPath: /usr/share/nginx/html

  volumes:
    - name: cloud-storage
      persistentVolumeClaim:
        claimName: cloud-pvc
